version: "3"
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-controller
    ports:
      - 8000:8080
      - 50001:50000
    volumes:
      - jenkins_home:/var/jenkins_home/
volumes:
  jenkins_home: